[package]
name = "ecsh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
aws-config = { version = "1.12.0", features = ["behavior-version-latest"] }
aws-sdk-ecs = "1.148.0"
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
toml = "1.1.6"
